
"""
Project Euler Problem 2:Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the 
previous two terms. Starting with 1 and 2, the first 10 terms are:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do 
not exceed four million, find the sum of the even-valued terms.
"""

a=1
b=2 
sum=0 
while a<=4000000:
 if a%2==0: 
   sum+=a
 c=a+b
 a,b=b,c
 print(c)

print(f"The sum of even valued terms in Fibonacci sequence is {sum}")

